
//! Autogenerated weights for `messaging`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.0.0
//! DATE: 2025-04-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Felixs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
//  pop
//  bench
//  pallet
//  --pallet=messaging
//  --extrinsic=ismp_get,ismp_on_response,ismp_on_timeout,ismp_post,remove,xcm_new_query,xcm_response
//  --steps=50
//  --output=./pallets/api/src/messaging/weights.rs
//  --template=./scripts/runtime-weight-template.hbs
//  --runtime=/Users/rmrf-2/code/pop-node/target/release/wbuild/pop-runtime-devnet/pop_runtime_devnet.wasm
//  --genesis-builder=runtime
//  --genesis-builder-preset=pop-devnet-dev

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for `messaging`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> messaging::WeightInfo for WeightInfo<T> {
	/// Storage: `Messaging::Messages` (r:100 w:100)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::IsmpRequests` (r:0 w:100)
	/// Proof: `Messaging::IsmpRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 100]`.
	fn remove(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `376 + x * (105 ±0)`
		//  Estimated: `3658 + x * (15317 ±0)`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 3658)
			// Standard Error: 27_837
			.saturating_add(Weight::from_parts(22_203_208, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(x.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(x.into())))
			.saturating_add(Weight::from_parts(0, 15317).saturating_mul(x.into()))
	}
	/// Storage: `Messaging::Messages` (r:1 w:1)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::XcmQueryTimeouts` (r:1 w:1)
	/// Proof: `Messaging::XcmQueryTimeouts` (`max_values`: None, `max_size`: Some(6406), added: 8881, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::QueryCounter` (r:1 w:1)
	/// Proof: `PolkadotXcm::QueryCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Messaging::XcmQueries` (r:0 w:1)
	/// Proof: `Messaging::XcmQueries` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::Queries` (r:0 w:1)
	/// Proof: `PolkadotXcm::Queries` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 1]`.
	fn xcm_new_query(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `16307`
		// Minimum execution time: 33_000_000 picoseconds.
		Weight::from_parts(35_912_244, 16307)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Messaging::XcmQueries` (r:1 w:0)
	/// Proof: `Messaging::XcmQueries` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Messages` (r:1 w:1)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Revive::AddressSuffix` (r:1 w:0)
	/// Proof: `Revive::AddressSuffix` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 1]`.
	fn xcm_response(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355 + x * (294 ±0)`
		//  Estimated: `16307 + x * (1797 ±0)`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_697_959, 16307)
			// Standard Error: 149_924
			.saturating_add(Weight::from_parts(9_702_040, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(x.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 1797).saturating_mul(x.into()))
	}
	/// Storage: `Messaging::IsmpRequests` (r:1 w:0)
	/// Proof: `Messaging::IsmpRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Messages` (r:1 w:1)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Revive::AddressSuffix` (r:1 w:0)
	/// Proof: `Revive::AddressSuffix` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 1]`.
	/// The range of component `y` is `[0, 1]`.
	fn ismp_on_response(x: u32, y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + x * (524 ±0) + y * (151 ±0)`
		//  Estimated: `3593 + x * (16507 ±21_766_596_034_741_860)`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(3_000_000, 3593)
			// Standard Error: 47_056
			.saturating_add(Weight::from_parts(11_736_195, 0).saturating_mul(x.into()))
			// Standard Error: 47_056
			.saturating_add(Weight::from_parts(277_011, 0).saturating_mul(y.into()))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(x.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
			.saturating_add(Weight::from_parts(0, 16507).saturating_mul(x.into()))
	}
	/// Storage: `Messaging::IsmpRequests` (r:1 w:0)
	/// Proof: `Messaging::IsmpRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Messages` (r:1 w:1)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2]`.
	/// The range of component `y` is `[0, 1]`.
	fn ismp_on_timeout(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159 + y * (42 ±0)`
		//  Estimated: `16307`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(7_893_704, 16307)
			// Standard Error: 52_605
			.saturating_add(Weight::from_parts(855_188, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Messaging::Messages` (r:1 w:1)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Messaging::IsmpRequests` (r:0 w:1)
	/// Proof: `Messaging::IsmpRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebe4bf2b1e0d50a47a6026ff9f89` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebe4bf2b1e0d50a47a6026ff9f89` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b822d5f9e7430a9c13023708b6e8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b822d5f9e7430a9c13023708b6e8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d2b7f8adb5263695b748b50b35e7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d2b7f8adb5263695b748b50b35e7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b6d3b50d11d63f5a16223d0f6192` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b6d3b50d11d63f5a16223d0f6192` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bcad1167844259b7475e67add0cf` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bcad1167844259b7475e67add0cf` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737c0b35a703d5af186e16b0b8b26a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737c0b35a703d5af186e16b0b8b26a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737a9bb2e4cb5ef3f3b83e18ecd62c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737a9bb2e4cb5ef3f3b83e18ecd62c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bc04fe0f0a74ebff15d2d87fdbb1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bc04fe0f0a74ebff15d2d87fdbb1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737b5d150daa95d0c51137f28408ba` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737b5d150daa95d0c51137f28408ba` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ede597e3a5ee230597ae65009027` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ede597e3a5ee230597ae65009027` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473843abb5f01c6b8d278b95bab27d7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473843abb5f01c6b8d278b95bab27d7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738d3edf6cbffbd715d91df9544259` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738d3edf6cbffbd715d91df9544259` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fbbb0dd84b2c05ab7e6c2e912be2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fbbb0dd84b2c05ab7e6c2e912be2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473516ff665c874f7d80a3094a2766f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473516ff665c874f7d80a3094a2766f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473157e0cfb3591a4031670f0bd0b59` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473157e0cfb3591a4031670f0bd0b59` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c2600acf6638dc572aba8bb7e17e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c2600acf6638dc572aba8bb7e17e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747370d530e6e97b84f2b9f5f31f0f1e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747370d530e6e97b84f2b9f5f31f0f1e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c2a55a808472cc90a56c9263e8c4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c2a55a808472cc90a56c9263e8c4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bcfa64038d41c7e5b13c56a3790e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473bcfa64038d41c7e5b13c56a3790e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747302abe5edca3db5f3a60882617054` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747302abe5edca3db5f3a60882617054` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f484690eb40af82a20f82dd43a40` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f484690eb40af82a20f82dd43a40` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739afaa33dccd1c2b5663a9fec3aa6` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739afaa33dccd1c2b5663a9fec3aa6` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473edb24a55dd96654731b01c5fa1ce` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473edb24a55dd96654731b01c5fa1ce` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473204326c0a899add1bb9a0e44017a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473204326c0a899add1bb9a0e44017a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738f97a59a48ba326530dcbb00fdb8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738f97a59a48ba326530dcbb00fdb8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473dc615e4d8f5e4c499a4ee16e7250` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473dc615e4d8f5e4c499a4ee16e7250` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747382ff59321a7eb8f0a981e8b30d45` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747382ff59321a7eb8f0a981e8b30d45` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ee1a18c63a6d8b4d22066227cfe9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ee1a18c63a6d8b4d22066227cfe9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b332273af6fa385aea8eabd929ff` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b332273af6fa385aea8eabd929ff` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747308d7352d7ef3b6c484dfc7ce4170` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747308d7352d7ef3b6c484dfc7ce4170` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736a3a8637e8e4441ed411038befc6` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736a3a8637e8e4441ed411038befc6` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747314f08dae9f0fabe5e14b1ee5d47b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747314f08dae9f0fabe5e14b1ee5d47b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747302610adfd3510c9eab269a6ec1b5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747302610adfd3510c9eab269a6ec1b5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d32f80b2876c566c3430e688efeb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d32f80b2876c566c3430e688efeb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735b92766ff94e59a786b6a9d0da86` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735b92766ff94e59a786b6a9d0da86` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a4fc3ec43ba8dcf284f9a4c66f13` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a4fc3ec43ba8dcf284f9a4c66f13` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b5247a619d23a30bdf3ff78fd89b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b5247a619d23a30bdf3ff78fd89b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747336e585a9e1ee1d17225dc509ae08` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747336e585a9e1ee1d17225dc509ae08` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f204de8a4423fc0f0768f6c44195` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f204de8a4423fc0f0768f6c44195` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739793d71a6b55c8409d727dcb6ea5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739793d71a6b55c8409d727dcb6ea5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736322c9c869ac42b212a820e89521` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736322c9c869ac42b212a820e89521` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473aabcf2a6dd2f496aa860a00848eb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473aabcf2a6dd2f496aa860a00848eb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747396da168082ed8d61a69d2dab4e34` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747396da168082ed8d61a69d2dab4e34` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473aaaff2ef1ddb3cb4b95ef0add4eb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473aaaff2ef1ddb3cb4b95ef0add4eb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733a095d2d68fed2e16a116323519e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733a095d2d68fed2e16a116323519e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c76bbd37cb335ea589d72db8524d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c76bbd37cb335ea589d72db8524d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473eeee49f922f8d8e3979af1c8309c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473eeee49f922f8d8e3979af1c8309c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735f3b12a201b21e36b7978712f54b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735f3b12a201b21e36b7978712f54b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747314b2d52d980ecf84a512ec317eef` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747314b2d52d980ecf84a512ec317eef` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e5819ce235d668ceb400b71b7540` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e5819ce235d668ceb400b71b7540` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ce5d8239372e6ade982bb6c1a08d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ce5d8239372e6ade982bb6c1a08d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747378d3ad24fa3dba23353cdddaebda` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747378d3ad24fa3dba23353cdddaebda` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a6f563c75970e55f0f579c663bc5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a6f563c75970e55f0f579c663bc5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738b5a8a1566887b5b4841e75f4546` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738b5a8a1566887b5b4841e75f4546` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b018b1374968c5229618cfd72044` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b018b1374968c5229618cfd72044` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c2e98b4f34c7eeaa858373ff21e8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c2e98b4f34c7eeaa858373ff21e8` (r:1 w:1)
	/// The range of component `x` is `[0, 8]`.
	/// The range of component `y` is `[0, 64]`.
	/// The range of component `z` is `[0, 10]`.
	/// The range of component `a` is `[0, 1]`.
	fn ismp_get(x: u32, y: u32, z: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `6544 + a * (4735374734983762797219812652248727552 ±340_282_366_920_938_463_463_374_607_431_768_211_455) + x * (249230249209671726169463823802564608 ±340_282_366_920_938_463_463_374_607_431_768_211_455) + y * (498460498419343452338927647605129216 ±340_282_366_920_938_463_463_374_607_431_768_211_455) + z * (3987683987354747618711421180841033728 ±340_282_366_920_938_463_463_374_607_431_768_211_455)`
		// Minimum execution time: 68_000_000 picoseconds.
		Weight::from_parts(74_320_247, 6544)
			// Standard Error: 38_420
			.saturating_add(Weight::from_parts(14_568, 0).saturating_mul(x.into()))
			// Standard Error: 5_136
			.saturating_add(Weight::from_parts(8_812, 0).saturating_mul(y.into()))
			// Standard Error: 31_448
			.saturating_add(Weight::from_parts(144_816, 0).saturating_mul(z.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(Weight::from_parts(0, 4735374734983762797219812652248727552).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 249230249209671726169463823802564608).saturating_mul(x.into()))
			.saturating_add(Weight::from_parts(0, 498460498419343452338927647605129216).saturating_mul(y.into()))
			.saturating_add(Weight::from_parts(0, 3987683987354747618711421180841033728).saturating_mul(z.into()))
	}
	/// Storage: `Messaging::Messages` (r:1 w:1)
	/// Proof: `Messaging::Messages` (`max_values`: None, `max_size`: Some(12842), added: 15317, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::IsmpRequests` (r:0 w:1)
	/// Proof: `Messaging::IsmpRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738bcc4d5639f6254cf5fb180c0f72` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738bcc4d5639f6254cf5fb180c0f72` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329c14ef481742eefb7788386c681` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747329c14ef481742eefb7788386c681` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473287e74fac42e4ec79f5df44ce538` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473287e74fac42e4ec79f5df44ce538` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738855267813169e1a708e4e75f5a4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738855267813169e1a708e4e75f5a4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732701a1cee50c8d6a53d46cd5ec9c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732701a1cee50c8d6a53d46cd5ec9c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b9b3aa15a2889c21b7dba485c2c9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b9b3aa15a2889c21b7dba485c2c9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739b94cb38b0eeacc24002a991f884` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739b94cb38b0eeacc24002a991f884` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a751421a4bc2ed95713fe54770be` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a751421a4bc2ed95713fe54770be` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747360dac5301eeb275913f0ea8cd5e1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747360dac5301eeb275913f0ea8cd5e1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f862082677fea2554a85a022ac4e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f862082677fea2554a85a022ac4e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fd50b6c6ca4e895c83d52a34a78b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473fd50b6c6ca4e895c83d52a34a78b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734557713d9ab03e150f5de5ff31fe` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74734557713d9ab03e150f5de5ff31fe` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c384b875cbf15d88c72f7fcdf46d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c384b875cbf15d88c72f7fcdf46d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f86067141771d95fda435ce4c9ed` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473f86067141771d95fda435ce4c9ed` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737bfab4afd6a9461416f2eef6c631` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737bfab4afd6a9461416f2eef6c631` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473162048f20318aed8443da4fc86a0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473162048f20318aed8443da4fc86a0` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e9199a3f6daaa9e08bc80c4fb6d2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e9199a3f6daaa9e08bc80c4fb6d2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733e3906031411b8a73b2a37e10c30` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733e3906031411b8a73b2a37e10c30` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473db5b8c06d688e761d750e08ec388` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473db5b8c06d688e761d750e08ec388` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cb972b1ef83734f649cf01a1cdf6` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cb972b1ef83734f649cf01a1cdf6` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473dc363d873b7bf73b7a48ca0044e1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473dc363d873b7bf73b7a48ca0044e1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747388b3ef1033bdb656252f25d7242f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747388b3ef1033bdb656252f25d7242f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e0fa58cab7cb166c7874dbdfeb3f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e0fa58cab7cb166c7874dbdfeb3f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747315fce57276d5b85a9cbf010fd172` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747315fce57276d5b85a9cbf010fd172` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737211ea27eda948b27e13fd22254b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737211ea27eda948b27e13fd22254b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747380ae933955b131824193a62133fe` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747380ae933955b131824193a62133fe` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730167e0cf40b01aac1362c3d671b3` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74730167e0cf40b01aac1362c3d671b3` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b1351345a92cbc925c15f3d9c0e1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b1351345a92cbc925c15f3d9c0e1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738b35c258e56421e62d5b5da9ea79` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738b35c258e56421e62d5b5da9ea79` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b3460961984ca24484abca1e6170` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b3460961984ca24484abca1e6170` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a4c6c073b4aab4d52f90ee49a4a2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473a4c6c073b4aab4d52f90ee49a4a2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473190bc10ab9a111e6bcf0170239a6` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473190bc10ab9a111e6bcf0170239a6` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebaba6223bec6ba065297feb9203` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ebaba6223bec6ba065297feb9203` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ac33d6918e95e1723cd1b37511cb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473ac33d6918e95e1723cd1b37511cb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b5c3e8ce0af22b7eaf23b1de6b08` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b5c3e8ce0af22b7eaf23b1de6b08` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737ff8123cb53fa51a8eed8457602a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74737ff8123cb53fa51a8eed8457602a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747326a44b9e2418ab22987b7899a8e3` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747326a44b9e2418ab22987b7899a8e3` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e248a1f77658a9204d311172361d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e248a1f77658a9204d311172361d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733d71d8db298f692188502bcb5578` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74733d71d8db298f692188502bcb5578` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d829600de0d3559b0af886d46a62` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473d829600de0d3559b0af886d46a62` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747372fee2e1674f54f62fbe87f8fc9e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747372fee2e1674f54f62fbe87f8fc9e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738657390e24e953d310f0c860266a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738657390e24e953d310f0c860266a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732d11743773c308577fb8136608b2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732d11743773c308577fb8136608b2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340b23a454414e4ca08a0895b8a82` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747340b23a454414e4ca08a0895b8a82` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747330227a1128899a06563f785b26c4` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747330227a1128899a06563f785b26c4` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747339211de95404ccc298bf7270ec80` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747339211de95404ccc298bf7270ec80` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e52954120cc73dc4a175a41586f1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e52954120cc73dc4a175a41586f1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738fb69ed7a2cfe714ab54b62310a9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74738fb69ed7a2cfe714ab54b62310a9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473278c2c4490fb7d4efd021217ce92` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473278c2c4490fb7d4efd021217ce92` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735e89703e0ce7cd3db3a41a7f8a37` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74735e89703e0ce7cd3db3a41a7f8a37` (r:1 w:1)
	/// The range of component `x` is `[0, 512]`.
	/// The range of component `y` is `[0, 1]`.
	fn ismp_post(x: u32, y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `16307 + x * (816 ±1_378_179_652_877_390) + y * (8448 ±661_526_233_381_146_880)`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(75_036_622, 16307)
			// Standard Error: 812
			.saturating_add(Weight::from_parts(3_284, 0).saturating_mul(x.into()))
			// Standard Error: 271_033
			.saturating_add(Weight::from_parts(344_817, 0).saturating_mul(y.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(Weight::from_parts(0, 816).saturating_mul(x.into()))
			.saturating_add(Weight::from_parts(0, 8448).saturating_mul(y.into()))
	}
}
