[package]
name = "chain-extension"
authors = ["[your_name] <[your_email]>"]
edition = "2021"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
ink = { version = "=5.0.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
    "derive",
], optional = true }

[dev-dependencies]
drink = { path = "../../../../pop-drink/drink" }
pop-sandbox = { path = "../../../pop-sandbox", default-features = false }

# If you are creating a custom runtime with `drink::create_sandbox_with_runtime!` macro, unfortunately you need to
# include these dependencies manually. Versions should match the ones in `Cargo.toml` of the `drink` crate.
frame-support = { version = "29.0.2" }
frame-system = { version = "29.0.0" }

[features]
default = ["std"]
std = ["ink/std", "pop-sandbox/std", "drink/std", "scale/std", "scale-info/std"]
ink-as-dependency = []
