[package]
authors = ["R0GUE <go@r0gue.io>"]
edition = "2021"
name = "dao"
version = "0.1.0"

[dependencies]
ink = { version = "5.1.0", default-features = false, features = ["ink-debug"] }
pop-api = { path = "../../../pop-api", default-features = false, features = [
	"fungibles",
] }

[dev-dependencies]
drink = { package = "pop-drink", git = "https://github.com/r0gue-io/pop-drink" }
env_logger = { version = "0.11.3" }
serde_json = "1.0.114"

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
e2e-tests = []
ink-as-dependency = []
std = [
	"ink/std",
	"pop-api/std",
]
