[package]
authors = [ "R0GUE <go@r0gue.io>" ]
edition = "2021"
name = "fungibles"
version = "0.1.0"

[package.metadata.ink-lang]
abi = "sol"

[lib]
path = "lib.rs"

[dependencies]
ink = { git = "https://github.com/use-ink/ink", default-features = false, features = [ "unstable-hostfn" ] }
pop-api = { path = "../../../pop-api-vnext", default-features = false, features = [ "fungibles" ] }

[dev-dependencies]
hex = { version = "0.4.3" }
scale-info = { version = "2" }

[features]
default = [ "std" ]
ink-as-dependency = [  ]
std = [ "ink/std", "pop-api/std" ]

[lints.rust.unexpected_cfgs]
check-cfg = [ 'cfg(ink_abi, values("ink", "sol", "all"))' ]
level = "warn"
