#!/bin/sh

set -eu

# Are deps installed
if ! command -v cargo > /dev/null 2>&1
then
    echo "cargo couldn't be found, please confirm your set up is properly configured."
    exit 1
else
    # Check Rust formatting
    if ! cargo +nightly fmt --all -- --check
    then
        echo "There are some code style issues."
        # shellcheck disable=SC2006
        echo "Run 'cargo +nightly fmt --all' first."
        exit 1
    fi
fi

if ! command -v taplo > /dev/null 2>&1
then
    echo "taplo couldn't be found. Please, refer to .githooks/README.md."
    exit 1
else
    # Check TOML formatting
    if ! taplo format --check
    then
        echo "There are some code style issues."
        echo "Run 'taplo fmt' first."
        exit 1
    fi
fi

if ! command -v zepter > /dev/null 2>&1
then
    echo "zepter couldn't be found. Please, refer to .githooks/README.md."
    exit 1
else
    # Check for feature formatting
    if ! zepter format features --ignore-feature unstable-hostfn
    then
        echo "There are some code style issues."
        echo "Run 'zepter format features --fix' first."
        exit 1
    fi
fi

exit 0
