[package]
authors = [ "R0GUE" ]
edition = "2021"
name = "sponsorhips"
version = "0.1.0"

[dependencies]
ink = { git = "https://github.com/peterwht/ink", branch = "peter/riscv", default-features = false }
polkavm-derive = "0.11.0"
pop-api = { path = "../../../../pop-api", default-features = false, features = [ "sponsorships" ] }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"ink/std",
	"pop-api/std",
]
