[package]
authors = [ "[your_name] <[your_email]>" ]
edition = "2021"
name = "nft-verifier"
version = "0.1.0"

[dependencies]
ink = { git = "https://github.com/r0gue-io/ink", branch = "sub0", default-features = false }
polkavm-derive = "0.11.0"
pop-api = { path = "../../../..", default-features = false, features = [ "messaging", "nonfungibles" ] }

[dev-dependencies]
hex = "0.4.3"

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"ink/std",
	"pop-api/std",
]
