[package]
authors = [ "R0GUE <go@r0gue.io>" ]
edition = "2021"
name = "nonfungibles"
version = "0.1.0"

[dependencies]
ink = { version = "5.1.0", default-features = false }
pop-api = { path = "../../../pop-api", default-features = false, features = [
	"nonfungibles",
] }

[dev-dependencies]
drink = { package = "pop-drink", git = "https://github.com/r0gue-io/pop-drink", branch = "chungquantin/feat-nfts", features = [ "devnet" ] }
env_logger = { version = "0.11.3" }
pallet-nfts = { git = "https://github.com/r0gue-io/pop-node" }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
serde_json = "1.0.114"

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"ink/std",
	"pop-api/std",
	"scale/std",
]
