version = "1"
pallet = "messaging"
extrinsic = "ismp_get,ismp_on_response,ismp_on_timeout,ismp_post,remove,xcm_new_query,xcm_response"
exclude_pallets = []
all = false
steps = 50
lowest_range_values = []
highest_range_values = []
repeat = 20
external_repeat = 1
json_output = false
no_median_slopes = false
no_min_squares = false
output = "./pallets/api/src/messaging/weights.rs"
template = "./scripts/runtime-weight-template.hbs"
output_pov_analysis = "median-slopes"
no_verify = false
extra = false
runtime = "/Users/rmrf-2/code/pop-node/target/release/wbuild/pop-runtime-devnet/pop_runtime_devnet.wasm"
allow_missing_host_functions = false
genesis_builder = "Runtime"
genesis_builder_preset = "pop-devnet-dev"
database_cache_size = 1024
list = false
no_storage_info = false
worst_case_map_values = 1000000
additional_trie_layers = 2
disable_proof_recording = false
skip_parameters = false
skip_confirm = false
no_build = false
