[package]
authors = [ "[your_name] <[your_email]>" ]
edition = "2021"
name = "nft-verifier"
version = "0.1.0"

[workspace]

[dependencies]
hex = { version = "0.4.3", default-features = false }
ink = { version = "5.1.1", default-features = false }
pop-api = { path = "../../../../pop-api", default-features = false, features = [ "fungibles", "messaging", "nonfungibles" ] }
sp-core = { version = "32.0.0", default-features = false }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"hex/std",
	"ink/std",
	"pop-api/std",
	"sp-core/std",
]
