[package]
edition = "2021"
name = "fungibles"
authors = ["R0GUE <go@r0gue.io>"]
version = "0.1.0"

[dependencies]
ink = { git = "https://github.com/peterwht/ink", branch = "peter/riscv", default-features = false }
pop-api-revive = { path = "../../..", default-features = false, features = ["fungibles"] }
polkavm-derive = "0.11.0"

[lib]
path = "lib.rs"

[features]
default = ["std"]
e2e-tests = []
ink-as-dependency = []
std = [
    "ink/std",
    "pop-api-revive/std",
]
