[package]
authors = [ "R0GUE <go@r0gue.io>" ]
edition = "2021"
name = "api_example_flipper"
version = "0.1.0"

[dependencies]
ink = { version = "=5.0.0", default-features = false, features = [ "ink-debug" ] }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
	"derive",
], optional = true }

[dev-dependencies]
drink = { path = "../../../../pop-drink/drink" }
pop-sandbox = { path = "../../../pop-sandbox", default-features = false }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
ink-as-dependency = [  ]
std = [ "ink/std", "pop-sandbox/std", "scale-info/std", "scale/std" ]
