[package]
authors = [ "r0gue <go@r0gue.io>" ]
edition = "2021"
name = "create_token_in_constructor"
version = "0.1.0"

[dependencies]
ink = { git = "https://github.com/peterwht/ink", branch = "peter/riscv", default-features = false }
polkavm-derive = "0.11.0"
pop-api-revive = { path = "../../..", default-features = false, features = [ "fungibles" ] }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"ink/std",
	"pop-api-revive/std",
]
