[package]
authors.workspace = true
description = "Exposes all the host functions that a contract can import."
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "pallet-revive-uapi"
repository.workspace = true
version = "0.1.0"

#[lints]
#workspace = true

[package.metadata.docs.rs]
features = [ "unstable-hostfn" ]
targets = [ "riscv64imac-unknown-none-elf" ]

[dependencies]
bitflags = { version = "1.3.2" }
codec = { features = [ "derive", "max-encoded-len" ], optional = true, workspace = true }
pallet-revive-proc-macro = { path = "../proc-macro" }
scale-info = { features = [ "derive" ], optional = true, workspace = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
polkavm-derive = { version = "0.21.0" }

[features]
default = [ "scale" ]
scale = [ "dep:codec", "scale-info" ]
unstable-hostfn = [  ]
