[package]
authors.workspace = true
default-run = "eth-rpc"
description = "An Ethereum JSON-RPC server for pallet-revive."
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "pallet-revive-eth-rpc"
repository.workspace = true
version = "0.1.0"

[[bin]]
name = "eth-rpc"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = [ "derive", "env" ] }
codec = { workspace = true, features = [ "derive" ] }
futures = { workspace = true, features = [ "thread-pool" ] }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = [ "full" ] }
log = { workspace = true }
pallet-revive = { workspace = true, default-features = true }
prometheus-endpoint = { workspace = true, default-features = true }
rlp = { workspace = true }
sc-cli = { workspace = true, default-features = true }
sc-rpc = { workspace = true, default-features = true }
sc-rpc-api = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sp-arithmetic = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-crypto-hashing = { workspace = true }
sp-runtime = { workspace = true, default-features = true }
sp-weights = { workspace = true, default-features = true }
sqlx = { workspace = true, features = [ "macros", "runtime-tokio", "sqlite" ] }
subxt = { workspace = true, default-features = true, features = [ "reconnecting-rpc-client" ] }
subxt-signer = { workspace = true, features = [ "unstable-eth" ] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [ "full" ] }

[dev-dependencies]
env_logger = { workspace = true }
pallet-revive-fixtures = { workspace = true, default-features = true }
pretty_assertions = { workspace = true }
static_init = { workspace = true }
substrate-cli-test-utils = { workspace = true }
subxt-signer = { workspace = true, features = [ "unstable-eth" ] }

[build-dependencies]
git2 = { workspace = true }
