name: setup-worker
description: |
  This action sets up a worker for use in other actions. It installs the
  necessary dependencies for building the project.

inputs:
  rust-components:
    description: Comma-separated list of components to be additionally installed for a new rust toolchain
    required: false

runs:
  using: "composite"

  steps:
    - name: Setup Ubuntu dependencies
      shell: bash
      run: sudo apt update && sudo apt install -y git clang curl libssl-dev llvm libudev-dev cmake protobuf-compiler

    - name: Free up space on runner
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Rust Setup
      shell: bash
      run: |
        rustup toolchain install stable --profile minimal --component rustfmt clippy
        rustup default stable
        rustup target add wasm32-unknown-unknown