[package]
name = "fund-dev-accounts"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "fund-dev-accounts"
path = "./main.rs"

[dependencies]
subxt = "0.34.0"
subxt-signer = "0.34.0"
tokio = { version = "1.36", features = ["macros", "time", "rt-multi-thread"] }
hex = "0.4.3"
array-bytes = "6.2.2"
log.workspace = true

sp-core.workspace = true
sp-runtime.workspace = true

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-runtime/std",
]
paseo = []

runtime-benchmarks = [
    "sp-runtime/runtime-benchmarks",
]

try-runtime = [
    "sp-runtime/try-runtime",
]