[package]
name = "fund-dev-accounts"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "fund-dev-accounts"
path = "./main.rs"

[dependencies]
log.workspace = true
subxt.workspace = true
subxt-signer.workspace = true
tokio.workspace = true

[features]
paseo = []