[package]
authors.workspace = true
description = "Procedural macros used in pallet_revive"
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "pallet-revive-proc-macro"
repository.workspace = true
version = "0.1.0"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { features = [ "full" ], workspace = true }
