[package]
authors.workspace = true
description = "Procedural macros used in pallet_revive"
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "pallet-revive-proc-macro"
repository.workspace = true
version = "0.1.0"

#[lints]
#workspace = true

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.86" }
quote = { version = "1.0.37" }
syn = { version = "2.0.87", features = [ "full" ] }
