[package]
authors = [ "R0GUE <go@r0gue.io>" ]
edition = "2021"
name = "create_collection_in_constructor"
version = "0.1.0"

[workspace]

[dependencies]
ink = { version = "5.1.0", default-features = false }
pop-api = { path = "../../..", default-features = false, features = [ "nonfungibles" ] }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
std = [
	"ink/std",
	"pop-api/std",
]
