[package]
authors = [ "[your_name] <[your_email]>" ]
edition = "2021"
name = "api_example_fungibles"
version = "0.1.0"

[dependencies]
ink = { version = "=5.0.0", default-features = false, features = [ "ink-debug" ] }
pop-api = { path = "../../../pop-api", default-features = false, features = [
	"fungibles",
] }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
	"derive",
], optional = true }

[dev-dependencies]
drink = { path = "../../../../pop-drink/drink" }
pop-sandbox = { path = "../../../pop-sandbox", default-features = false }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"ink/std",
	"pop-api/std",
	"pop-sandbox/std",
	"scale-info/std",
	"scale/std",
]
