name: Initialize
description: This action initializes a runner for use in other actions.
inputs:
  cache:
    description: Whether to enable Rust caching. Defaults to true.
    default: "true"
  cache-all-crates:
    description: Whether all crates should be cached, or only dependent crates. Defaults to true.
    default: "true"
  cache-directories:
    description: Additional non-workspace directories to be cached, separated by newlines.
  cache-on-failure:
    description: Cache even if the build fails. Defaults to false.
    default: "true"
  cache-key:
    description: An additional optional key to be added. Useful for jobs utilizing a matrix.

runs:
  using: "composite"
  steps:
    - name: Setup Ubuntu dependencies
      shell: bash
      run: sudo apt update && sudo apt install -y protobuf-compiler

    - name: Free up space on runner
      shell: bash
      run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Rust Cache
      if: ${{ inputs.cache == 'true' }}
      uses: Swatinem/rust-cache@v2.8.0
      with:
        cache-all-crates: ${{ inputs.cache-all-crates }}
        cache-directories: ${{ inputs.cache-directories }}
        cache-on-failure: ${{ inputs.cache-on-failure }}
        key: ${{ inputs.cache-key }}
