name: Initialize
description: This action initializes a runner for use in other actions.
inputs:
  cache-key:
    description: "The key to be used for the cache"

runs:
  using: "composite"
  steps:
    - name: Setup Ubuntu dependencies
      shell: bash
      run: sudo apt update && sudo apt install -y protobuf-compiler

    - name: Free up space on runner
      shell: bash
      run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3
      with:
        cache-on-failure: true
        cache-all-crates: true
        key: ${{ inputs.cache-key }}