[package]
authors = [ "[your_name] <[your_email]>" ]
edition = "2021"
name = "flipper"
version = "0.1.0"

[dependencies]
ink = { git = "https://github.com/peterwht/ink", branch = "peter/riscv", default-features = false }
polkavm-derive = "0.11.0"

pop-api-revive = { path = "../../..", default-features = false, features = [ "fungibles" ] }

[dev-dependencies]
ink_e2e = { version = "5.0.0" }

[lib]
path = "lib.rs"

[features]
default = [ "std" ]
e2e-tests = [  ]
ink-as-dependency = [  ]
std = [
	"ink/std",
]
